"""Added nutrition table

Revision ID: 04f92c93d8a7
Revises: b01bbed81930
Create Date: 2023-12-12 21:38:11.148522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04f92c93d8a7'
down_revision = 'b01bbed81930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition',
    sa.Column('food_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('total_fat', sa.Float(), nullable=True),
    sa.Column('cholesterol', sa.Integer(), nullable=True),
    sa.Column('carbohydrate', sa.Float(), nullable=True),
    sa.Column('sugars', sa.Float(), nullable=True),
    sa.Column('dietary_fiber', sa.Float(), nullable=True),
    sa.Column('vitamin_a', sa.Integer(), nullable=True),
    sa.Column('vitamin_b_1', sa.Integer(), nullable=True),
    sa.Column('vitamin_b_2', sa.Integer(), nullable=True),
    sa.Column('vitamin_b_6', sa.Integer(), nullable=True),
    sa.Column('vitamin_b_9', sa.Integer(), nullable=True),
    sa.Column('vitamin_b_12', sa.Integer(), nullable=True),
    sa.Column('vitamin_c', sa.Integer(), nullable=True),
    sa.Column('vitamin_d', sa.Integer(), nullable=True),
    sa.Column('vitamin_e', sa.Integer(), nullable=True),
    sa.Column('vitamin_k', sa.Integer(), nullable=True),
    sa.Column('canxi', sa.Integer(), nullable=True),
    sa.Column('phospho', sa.Integer(), nullable=True),
    sa.Column('fe', sa.Integer(), nullable=True),
    sa.Column('magie', sa.Integer(), nullable=True),
    sa.Column('zn', sa.Integer(), nullable=True),
    sa.Column('natri', sa.Integer(), nullable=True),
    sa.Column('iod', sa.Integer(), nullable=True),
    sa.Column('omega_3', sa.Integer(), nullable=True),
    sa.Column('omega_6', sa.Integer(), nullable=True),
    sa.Column('omega_9', sa.Integer(), nullable=True),
    sa.CheckConstraint('canxi >= 0', name=op.f('ck_nutrition_canxi')),
    sa.CheckConstraint('carbohydrate >= 0', name=op.f('ck_nutrition_carbohydrate')),
    sa.CheckConstraint('cholesterol >= 0', name=op.f('ck_nutrition_cholesterol')),
    sa.CheckConstraint('dietary_fiber >= 0', name=op.f('ck_nutrition_dietary_fiber')),
    sa.CheckConstraint('fe >= 0', name=op.f('ck_nutrition_fe')),
    sa.CheckConstraint('iod >= 0', name=op.f('ck_nutrition_iod')),
    sa.CheckConstraint('magie >= 0', name=op.f('ck_nutrition_magie')),
    sa.CheckConstraint('natri >= 0', name=op.f('ck_nutrition_natri')),
    sa.CheckConstraint('omega_3 >= 0', name=op.f('ck_nutrition_omega_3')),
    sa.CheckConstraint('omega_6 >= 0', name=op.f('ck_nutrition_omega_6')),
    sa.CheckConstraint('omega_9 >= 0', name=op.f('ck_nutrition_omega_9')),
    sa.CheckConstraint('phospho >= 0', name=op.f('ck_nutrition_phospho')),
    sa.CheckConstraint('protein >= 0', name=op.f('ck_nutrition_protein')),
    sa.CheckConstraint('sugars >= 0', name=op.f('ck_nutrition_sugars')),
    sa.CheckConstraint('total_fat >= 0', name=op.f('ck_nutrition_total_fat')),
    sa.CheckConstraint('vitamin_a >= 0', name=op.f('ck_nutrition_vitamin_a')),
    sa.CheckConstraint('vitamin_b_1 >= 0', name=op.f('ck_nutrition_vitamin_b_1')),
    sa.CheckConstraint('vitamin_b_12 >= 0', name=op.f('ck_nutrition_vitamin_b_12')),
    sa.CheckConstraint('vitamin_b_2 >= 0', name=op.f('ck_nutrition_vitamin_b_2')),
    sa.CheckConstraint('vitamin_b_6 >= 0', name=op.f('ck_nutrition_vitamin_b_6')),
    sa.CheckConstraint('vitamin_b_9 >= 0', name=op.f('ck_nutrition_vitamin_b_9')),
    sa.CheckConstraint('vitamin_c >= 0', name=op.f('ck_nutrition_vitamin_c')),
    sa.CheckConstraint('vitamin_d >= 0', name=op.f('ck_nutrition_vitamin_d')),
    sa.CheckConstraint('vitamin_e >= 0', name=op.f('ck_nutrition_vitamin_e')),
    sa.CheckConstraint('vitamin_k >= 0', name=op.f('ck_nutrition_vitamin_k')),
    sa.CheckConstraint('zn >= 0', name=op.f('ck_nutrition_zn')),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name=op.f('fk_nutrition_food_id_food')),
    sa.PrimaryKeyConstraint('food_id', name=op.f('pk_nutrition'))
    )
    op.create_index(op.f('ix_nutrition_food_id'), 'nutrition', ['food_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrition_food_id'), table_name='nutrition')
    op.drop_table('nutrition')
    # ### end Alembic commands ###
