"""empty message

Revision ID: 47ac0d408a6c
Revises: 
Create Date: 2023-06-27 01:45:45.454544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47ac0d408a6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exercise_type', sa.Enum('CARDIO', 'STRENGTH', name='exercisetype'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('burning_type', sa.Enum('CPH', 'CPS', name='burningtype'), nullable=False),
    sa.Column('burned_calories', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise'))
    )
    op.create_index(op.f('ix_exercise_id'), 'exercise', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=True)
    op.create_table('food',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.Enum('BOWL', 'CUP', 'GRAM', name='foodunit'), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='foodstatus'), nullable=False),
    sa.CheckConstraint('calories > 0', name=op.f('ck_food_calories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food'))
    )
    op.create_index(op.f('ix_food_id'), 'food', ['id'], unique=False)
    op.create_index(op.f('ix_food_name'), 'food', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('diary',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('breakfast_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('lunch_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('dining_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('maximum_calorie_intake', sa.Integer(), nullable=False),
    sa.Column('total_calorie_intake', sa.Integer(), nullable=False),
    sa.CheckConstraint('maximum_calorie_intake >= 0', name=op.f('ck_diary_maximum_calorie_intake')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_diary_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diary')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('uq_diary_user_id'))
    )
    op.create_index(op.f('ix_diary_date'), 'diary', ['date'], unique=False)
    op.create_index(op.f('ix_diary_id'), 'diary', ['id'], unique=False)
    op.create_index(op.f('ix_diary_user_id'), 'diary', ['user_id'], unique=False)
    op.create_table('food_diary',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('meal_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('food_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 1', name=op.f('ck_food_diary_quantity')),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name=op.f('fk_food_diary_food_id_food')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_diary')),
    sa.UniqueConstraint('meal_id', 'food_id', name=op.f('uq_food_diary_meal_id'))
    )
    op.create_index('(no name)', 'food_diary', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_diary_food_id'), 'food_diary', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_diary_id'), 'food_diary', ['id'], unique=False)
    op.create_index(op.f('ix_food_diary_meal_id'), 'food_diary', ['meal_id'], unique=False)
    op.create_table('food_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('food_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('number_of_uses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name=op.f('fk_food_history_food_id_food')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_food_history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_history'))
    )
    op.create_index(op.f('ix_food_history_food_id'), 'food_history', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_history_id'), 'food_history', ['id'], unique=False)
    op.create_index(op.f('ix_food_history_number_of_uses'), 'food_history', ['number_of_uses'], unique=False)
    op.create_index(op.f('ix_food_history_user_id'), 'food_history', ['user_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', name='userprofilegender'), nullable=False),
    sa.Column('starting_weight', sa.Float(), nullable=False),
    sa.Column('current_weight', sa.Float(), nullable=False),
    sa.Column('desired_weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('goal', sa.Enum('LOSE_WEIGHT', 'MAINTAIN_WEIGHT', 'GAIN_WEIGHT', name='userprofilegoal'), nullable=False),
    sa.Column('year_of_birth', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='userprofilestatus'), nullable=False),
    sa.Column('activity_level', sa.Enum('NOT_VERY_ACTIVE', 'LIGHTLY_ACTIVE', 'ACTIVE', 'VERY_ACTIVE', name='userprofileactivitylevel'), nullable=False),
    sa.Column('maximum_calorie_intake', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_profile_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile'))
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_food_history_user_id'), table_name='food_history')
    op.drop_index(op.f('ix_food_history_number_of_uses'), table_name='food_history')
    op.drop_index(op.f('ix_food_history_id'), table_name='food_history')
    op.drop_index(op.f('ix_food_history_food_id'), table_name='food_history')
    op.drop_table('food_history')
    op.drop_index(op.f('ix_food_diary_meal_id'), table_name='food_diary')
    op.drop_index(op.f('ix_food_diary_id'), table_name='food_diary')
    op.drop_index(op.f('ix_food_diary_food_id'), table_name='food_diary')
    op.drop_index('(no name)', table_name='food_diary')
    op.drop_table('food_diary')
    op.drop_index(op.f('ix_diary_user_id'), table_name='diary')
    op.drop_index(op.f('ix_diary_id'), table_name='diary')
    op.drop_index(op.f('ix_diary_date'), table_name='diary')
    op.drop_table('diary')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_food_name'), table_name='food')
    op.drop_index(op.f('ix_food_id'), table_name='food')
    op.drop_table('food')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_id'), table_name='exercise')
    op.drop_table('exercise')
    # ### end Alembic commands ###
