"""empty message

Revision ID: 497b14a8f689
Revises: de544c14c093
Create Date: 2023-06-27 03:09:02.292726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497b14a8f689'
down_revision = 'de544c14c093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_food_history_user_id'), 'food_history', ['user_id', 'food_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_food_history_user_id'), 'food_history', type_='unique')
    # ### end Alembic commands ###
