"""empty message

Revision ID: dc743877474c
Revises: 70d5e81628cd
Create Date: 2023-05-13 16:44:30.429278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc743877474c'
down_revision = '70d5e81628cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exercise_type', sa.Enum('CARDIO', 'STRENGTH', name='exercisetype'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('burning_type', sa.Enum('CPH', 'CPS', name='burningtype'), nullable=False),
    sa.Column('burned_calories', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise'))
    )
    op.create_index(op.f('ix_exercise_id'), 'exercise', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_id'), table_name='exercise')
    op.drop_table('exercise')
    # ### end Alembic commands ###
