"""empty message

Revision ID: de544c14c093
Revises: 47ac0d408a6c
Create Date: 2023-06-27 03:02:28.495486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de544c14c093'
down_revision = '47ac0d408a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
